name = "LorentzVectorHEP"
uuid = "f612022c-142a-473f-8cfd-a09cf3793c6c"
authors = ["Jerry Ling <proton@jling.dev> and contributors"]
version = "0.1.8"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
LorentzVectorHEPStaticArraysExt = "StaticArrays"

[compat]
LinearAlgebra = "1"
StaticArrays = "1"
julia = "^1.6"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
