name = "LorentzVectorHEP"
uuid = "f612022c-142a-473f-8cfd-a09cf3793c6c"
authors = ["Jerry Ling <proton@jling.dev> and contributors"]
version = "0.1.0"

[deps]
LorentzVectors = "3f54b04b-17fc-5cd4-9758-90c048d965e3"

[compat]
julia = "1.6^"
LorentzVectors = "0.4.2^"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
